#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

query = ARGV.join(" ").gsub("\"", "")

require "sqlite3"

db = SQLite3::Database.open "cards.db"

db.execute(
  <<-QUERY
    SELECT cmc,name,manaCost,power,toughness,type
    FROM cards
    WHERE name LIKE "%#{query}%"
    ORDER BY name
  QUERY
) do |row|
  pow_tough = " [#{row[3]}/#{row[4]}] " unless row[3] == ""
  puts "#{row[0]}  #{row[1]}  #{row[2]} #{pow_tough} #{row[5]}"
end
